language: node_js
node_js:
  - "node"
  - "10"
  - "12"
  - "14"
before_script:
  - npm install -g istanbul codecov
script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --exit -R spec && codecov
